# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main", "dev", "45-continuous-integration-mysql" ]
  pull_request:
    branches: [ "main", "dev", "45-continuous-integration-mysql" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        ports:
          - "3306:3306"
        env:
            MYSQL_HOST: 127.0.0.1
            MYSQL_DB: github_actions_test
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        options: --health-cmd="mysqladmin ping -h 127.0.0.1" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.1'
          bundler-cache: true

      # - name: Wait for MySQL to be ready
      #   run: |
      #       until mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES;"; do
      #           echo "Waiting for MySQL to be ready..."
      #           sleep 5
      #       done
      # Add or replace database setup steps here
      - name: Wait for MySQL to launch
        run: |
            sleep 10
            mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES;"
      - name: Set up database schema
        env:
          RAILS_ENV: test
          DATABASE_PORT: 3306
        run:
            bin/rails db:create
      - name: Load the database
        env:
          RAILS_ENV: test
          DATABASE_PORT: 3306
        run:
            bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # v1.179.1
        with:
          ruby-version: '3.4.1'
          bundler-cache: true
      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop
      # Add or replace any other lints here
      - name: Security audit dependencies
        run: bin/bundler-audit --update
      - name: Security audit application code
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bin/rubocop --parallel
